### ISSUE TITLE
Hierarchical Queue Capability Can Exceed Cluster Resources, Causing Validation Failures

### ISSUE THREAD

**Issue by zjj2wry** [volcano-sh/volcano#4819]
### Description

In Volcano's hierarchical queue mode, queues can be created with `capability` that exceeds the cluster's total resources or parent queue's capability. While the scheduler validates that `child.capability <= parent.capability` during scheduling, this validation **runs too late** (during OnSessionOpen, not at queue creation) and can **abort the entire scheduling cycle** when violated. Additionally, there is **no validation** that the root queue's capability does not exceed cluster total resources, leading to misleading configurations.

#### Queue Configuration (Invalid but Accepted)

**Cluster actual resources**: 100 CPU, 200Gi memory

```yaml

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: org-1
spec:
  parent: root
  weight: 1
  capability:
    cpu: "200"
    memory: "400Gi"
  # Violates: org-1.capability (200 CPU) > root.capability (100 CPU)
  # Violates: org-1.memory (400Gi) > root.memory (200Gi)
  guarantee:
    cpu: "50"
```

**Problems**:
- org-1.capability.cpu (200) > cluster total (100) ✗
- org-1.capability.memory (400Gi) > cluster total (200Gi) ✗
- Since root.capability is auto-set to cluster total, this also means:
  - org-1.capability (200, 400Gi) > root.capability (100, 200Gi) ✗

#### What Happens

1. **Queue creation succeeds**:
```bash
kubectl apply -f queues.yaml
# queue.scheduling.volcano.sh/org-1 created
```

**No error or warning!**

2. **Scheduler detects parent-child violation and aborts**:

When the next scheduling cycle runs, `checkHierarchicalQueue` executes:

```go
// Checks: root.capability >= org-1.capability
if attr.capability.LessPartly(childAttr.capability, api.Zero) {
    return fmt.Errorf("queue <%s> capability <%s> is less than its child queue <%s> capability <%s>",
        attr.name, attr.capability, childAttr.name, childAttr.capability)
}
```

**Scheduler log shows**:
```
E1216 10:00:00.123456 capacity.go:600] Failed to check queue's hierarchical structure,
error: queue <root> capability <cpu:100000,memory:214748364800> is less than its child queue <org-1>
capability <cpu:200000,memory:429496729600>
```

**Result**: `OnSessionOpen` returns `false`, causing:
- The entire scheduling cycle to be aborted
- **ALL jobs in ALL queues** fail to schedule (not just org-1)
- No pods are scheduled until the queue configuration is fixed
- All PodGroups remain in `Pending` state with no helpful error message

### Expected Behavior

When creating or updating queues, the system should:

1. **Validate at creation time**: Reject queue creation/update if `queue.capability > cluster.totalResource`
2. **Validate parent-child relationship**: Reject if `child.capability > parent.capability` (already exists)
3. **Fail fast with clear error**: Return a validation error explaining the constraint violation
4. **Prevent invalid state**: Never allow configurations that will cause scheduling failures

### Actual Behavior

1. **Queue creation succeeds** even when `capability > totalResource` or `child.capability > parent.capability`
2. **No validation error** is returned to the user
3. **Scheduler validates parent-child relationship during OnSessionOpen**
4. **If `child.capability > parent.capability`**: Entire scheduling cycle aborts (similar to guarantee validation issue)
5. **If `root.capability > totalResource`**: No error, but misleading configuration

#### Queue Creation Has No Validation for Cluster Limits

The queue validation webhook and controller do not check if capability exceeds cluster total resources.

#### Scheduler Validates Parent-Child Capability During OnSessionOpen

The capacity plugin validates parent-child capability relationship in `checkHierarchicalQueue` at [capacity.go:779-783](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/capacity/capacity.go#L779-L783):

```go
// Check if the parent queue's capability is less than the child queue's capability
if attr.capability.LessPartly(childAttr.capability, api.Zero) {
    return fmt.Errorf("queue <%s> capability <%s> is less than its child queue <%s> capability <%s>",
        attr.name, attr.capability, childAttr.name, childAttr.capability)
}
```

This validation runs during `OnSessionOpen` (same as guarantee validation), which means:

1. **Validation only runs during scheduling cycles**, not at queue creation time
2. **Error is only logged** - users don't see it unless they check scheduler logs
3. **Returns false from checkHierarchicalQueue** - this **aborts the entire scheduling cycle** for all queues
4. **No feedback to queue creator** - the queue is created successfully in Kubernetes
5. **Entire cluster becomes unschedulable** - all jobs fail, not just jobs in the invalid queue

### What version of Volcano are you using?

1.13

**Comment by hajnalmt** [comment]
Thank you for reporting this issue.
We shall add a validation webhook for this probably!

**Comment by zjj2wry** [comment]
> Thank you for reporting this issue. We shall add a validation webhook for this probably!

`Failed to check queue's hierarchical structure` will cause scheduler panic.

```golang
	ssn.AddPrePredicateFn(cp.Name(), func(task *api.TaskInfo) error {
		+ if !readyToSchedule {
		+	klog.V(3).Infof("Capacity plugin failed to check queue's hierarchical structure!")
		+	return fmt.Errorf("capacity plugin not ready: queue hierarchical structure check failed")
		+ }

		state := &capacityState{
			queueAttrs: make(map[api.QueueID]*queueAttr),
		}

		for _, queue := range cp.queueOpts {
			state.queueAttrs[queue.queueID] = queue.Clone()
		}

		ssn.GetCycleState(task.UID).Write(capacityStateKey, state)
		return nil
	})
```

```bash
E1217 09:50:24.019255       1 capacity.go:600] Failed to check queue's hierarchical structure, error: queue <org-2> deserved resources <cpu 50000.00, memory 107374182400.00> are less than the sum of its child queues' deserved resources <cpu 55000.00, memory 10737418240.00>
...
E1217 09:50:24.020081       1 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
        goroutine 508 [running]:
        k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3006188, 0xc000d6b2f0}, {0x2776dc0, 0x49eefd0})
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:132 +0xbc
        k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x3006890, 0xc000154620}, {0x2776dc0, 0x49eefd0}, {0x0, 0x0, 0xc000e4d2a8?})
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0x116
        k8s.io/apimachinery/pkg/util/runtime.HandleCrashWithContext({0x3006890, 0xc000154620}, {0x0, 0x0, 0x0})
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:78 +0x5a
        panic({0x2776dc0?, 0x49eefd0?})
                /usr/local/go/src/runtime/panic.go:787 +0x132
        volcano.sh/volcano/pkg/scheduler/api.(*Resource).Clone(...)
                /go/src/volcano.sh/volcano/pkg/scheduler/api/resource_info.go:143
        volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*queueAttr).Clone(0xc000bec5a0)
                /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:952 +0x72b
        volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).OnSessionOpen.func5(0xc000c9c7e0)
                /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:235 +0xce
        volcano.sh/volcano/pkg/scheduler/framework.(*Session).PrePredicateFn(0xc0002a6008, 0xc000c9c7e0)
                /go/src/volcano.sh/volcano/pkg/scheduler/framework/session_plugins.go:786 +0x118
        volcano.sh/volcano/pkg/scheduler/actions/preempt.(*Action).preempt(0xc00060a720, 0xc0002a6008, 0xc00045a900, 0xc000c9c7e0, 0xc00045a920, {0x2fd6840, 0xc000e142d8})
                /go/src/volcano.sh/volcano/pkg/scheduler/actions/preempt/preempt.go:286 +0x7e
        volcano.sh/volcano/pkg/scheduler/actions/preempt.(*Action).Execute(0xc00060a720, 0xc0002a6008)
                /go/src/volcano.sh/volcano/pkg/scheduler/actions/preempt/preempt.go:181 +0x1591
        volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000186600)
                /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:130 +0x36a
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1({0x0?, 0x0?})
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x13
        k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1({0x3006890?, 0xc000154620?}, 0x419074?)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:255 +0x51
        k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext({0x3006890, 0xc000154620}, 0xc000e4df50, {0x2fd7460, 0xc000d6a270}, 0x1)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xe5
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x19c3e60?, {0x2fd7460?, 0xc000d6a270?}, 0x56?, 0xc000940300?)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x46
        k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f0a220, 0x3b9aca00, 0x0, 0x1, 0xc000154620)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:210 +0x7f
        k8s.io/apimachinery/pkg/util/wait.Until(...)
                /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:163
        created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run in goroutine 177
                /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:96 +0x1a7
 >
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22d54eb]

goroutine 508 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x3006890, 0xc000154620}, {0x2776dc0, 0x49eefd0}, {0x0, 0x0, 0xc000e4d2a8?})
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:114 +0x1a9
k8s.io/apimachinery/pkg/util/runtime.HandleCrashWithContext({0x3006890, 0xc000154620}, {0x0, 0x0, 0x0})
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:78 +0x5a
panic({0x2776dc0?, 0x49eefd0?})
        /usr/local/go/src/runtime/panic.go:787 +0x132
volcano.sh/volcano/pkg/scheduler/api.(*Resource).Clone(...)
        /go/src/volcano.sh/volcano/pkg/scheduler/api/resource_info.go:143
volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*queueAttr).Clone(0xc000bec5a0)
        /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:952 +0x72b
volcano.sh/volcano/pkg/scheduler/plugins/capacity.(*capacityPlugin).OnSessionOpen.func5(0xc000c9c7e0)
        /go/src/volcano.sh/volcano/pkg/scheduler/plugins/capacity/capacity.go:235 +0xce
volcano.sh/volcano/pkg/scheduler/framework.(*Session).PrePredicateFn(0xc0002a6008, 0xc000c9c7e0)
        /go/src/volcano.sh/volcano/pkg/scheduler/framework/session_plugins.go:786 +0x118
volcano.sh/volcano/pkg/scheduler/actions/preempt.(*Action).preempt(0xc00060a720, 0xc0002a6008, 0xc00045a900, 0xc000c9c7e0, 0xc00045a920, {0x2fd6840, 0xc000e142d8})
        /go/src/volcano.sh/volcano/pkg/scheduler/actions/preempt/preempt.go:286 +0x7e
volcano.sh/volcano/pkg/scheduler/actions/preempt.(*Action).Execute(0xc00060a720, 0xc0002a6008)
        /go/src/volcano.sh/volcano/pkg/scheduler/actions/preempt/preempt.go:181 +0x1591
volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000186600)
        /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:130 +0x36a
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1({0x0?, 0x0?})
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x13
k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1({0x3006890?, 0xc000154620?}, 0x419074?)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:255 +0x51
k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext({0x3006890, 0xc000154620}, 0xc000e4df50, {0x2fd7460, 0xc000d6a270}, 0x1)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xe5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x19c3e60?, {0x2fd7460?, 0xc000d6a270?}, 0x56?, 0xc000940300?)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x46
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f0a220, 0x3b9aca00, 0x0, 0x1, 0xc000154620)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:210 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/volcano.sh/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:163
created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run in goroutine 177
        /go/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:96 +0x1a7
```

**Comment by hajnalmt** [comment]
The panic is caused by a not ininitalized attribute.
You ran into this issue I think:
https://github.com/volcano-sh/volcano/issues/4673 
It was fixed with this PR:
https://github.com/volcano-sh/volcano/pull/4611
Cherry-picks are also merged:
https://github.com/volcano-sh/volcano/pull/4694
https://github.com/volcano-sh/volcano/pull/4695

**Comment by zjj2wry** [comment]
> The panic is caused by a not ininitalized attribute. You ran into this issue I think: [#4673](https://github.com/volcano-sh/volcano/issues/4673) It was fixed with this PR: [#4611](https://github.com/volcano-sh/volcano/pull/4611) Cherry-picks are also merged: [#4694](https://github.com/volcano-sh/volcano/pull/4694) [#4695](https://github.com/volcano-sh/volcano/pull/4695)

Thank you very much, how can I get the fixed image for release-1.3?

**Comment by hajnalmt** [comment]
As far as I know there isn't an updated image release out yet 🫤 I will get back to you when I will have some information regarding this.

**Comment by zjj2wry** [comment]
> Thank you for reporting this issue. We shall add a validation webhook for this probably!

Adding a webhook doesn't seem to solve this problem. If nodes scale down or GPU cards fail, the capability can still be exceeded. Currently, when the scheduler fails hierarchy queue checks, the entire scheduler becomes non-functional, which is too dangerous.

Suggested:
- Strict validation at queue creation time 
- Warning-only mode at runtime
- Disable only the affected queue instead of the entire scheduler

**Comment by JesseStutler** [comment]
> Disable only the affected queue instead of the entire scheduler

Correct, it's also what I want

@zjj2wry Do you have interest in applying your suggestions? They're great solutions.

**Comment by JesseStutler** [comment]
> As far as I know there isn't an updated image release out yet 🫤 I will get back to you when I will have some information regarding this.


> > The panic is caused by a not ininitalized attribute. You ran into this issue I think: [#4673](https://github.com/volcano-sh/volcano/issues/4673) It was fixed with this PR: [#4611](https://github.com/volcano-sh/volcano/pull/4611) Cherry-picks are also merged: [#4694](https://github.com/volcano-sh/volcano/pull/4694) [#4695](https://github.com/volcano-sh/volcano/pull/4695)
> 
> Thank you very much, how can I get the fixed image for release-1.3?

I will release v1.13.1 this week

**Comment by JesseStutler** [comment]
https://github.com/volcano-sh/volcano/releases/tag/v1.13.1 The v1.13.1 has just been released, please use this version

**Comment by JesseStutler** [comment]
Done with #4864
